name: Github Pages

on:
  push:
    branches:
    - master

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    container:
      image: "swift:5.6"
    steps:
    - name: Checkout
      uses: actions/checkout@v1
        
    - name: Build Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make

    - name: Generate Site
      run: publish generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./Output
